spring:
 profiles:
     active: dev
---
server:
  port: 8001
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 123456
    dbcp2:
          min-idle: 5                                           # 数据库连接池的最小维持连接数
          initial-size: 5                                       # 初始化连接数
          max-total: 5                                          # 最大连接数
          max-wait-millis: 200                                 # 等待连接获取的最大超时时间
  application:
    name: provider-dept                                         #注册进入eureka的服务名         
  
mybatis:
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  type-aliases-package: com.infoex.pojo

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: provider-dept-8001     #注册进入eureka的服务的实列名
    prefer-ip-address: true            #实例名的前缀使用Ip地址

info:
  app.name: microserver-provider-dept
  company.name: infoex
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 8001
spring:
  profiles: test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: 123456
    dbcp2:
          min-idle: 5                                           # 数据库连接池的最小维持连接数
          initial-size: 5                                       # 初始化连接数
          max-total: 5                                          # 最大连接数
          max-wait-millis: 200                                 # 等待连接获取的最大超时时间
  application:
    name: provider-dept                                         #注册进入eureka的服务名         
  
mybatis:
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  type-aliases-package: com.infoex.pojo

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: provider-dept-8001     #注册进入eureka的服务的实列名
    prefer-ip-address: true            #实例名的前缀使用Ip地址

info:
  app.name: microserver-provider-dept
  company.name: infoex
  build.artifactId: $project.artifactId$
  build.version: $project.version$